version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/course-buddy
      - PORT=5001
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - course-buddy-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://YOUR_EC2_PUBLIC_IP:5001
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - course-buddy-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - course-buddy-network
    environment:
      - MONGO_INITDB_DATABASE=course-buddy

networks:
  course-buddy-network:
    driver: bridge

volumes:
  mongodb_data: 